Combined changes to baseline nb-wrangler, wrangler image, wrangler pipelines, roman-20.0.0 classic image from spi-injection. - Added CODEOWNERS to prevent normal collaborators from pushing to most of mail,  must PR. - Modified existing floating and frozen build workflows to ignore nbw-spec-archive/ and deployments/wrangler for triggering. - Modified existing quality and security workflows to ignore nbw-spec-archive/,  updated to those workflows to Python-3.13. - Added build-wrangler workflow to build, test, scan, and push an image based on a merged spec. - Added validate-wrangler workflow to validate a spec and merge the PR triggering a build. - Added image-repack script to squash an image to a single layer preserving key metadata.  This is configurable for wrangler workflow. - Moved README.md's image .png down into the docs/ directory to avoid top level clutter. - Changes to common Dockerfile:   - relocated PIP_TOOLS_CACHE_DIR ENV var to top of Dockerfile   - added jq package to support yq used to slice-and-dice wrangler specs on the CLI   - dropped cargo and rustc (no longer needed) to save ~0.5-1G of image space.   - consolidated directory copies   - added code to explicitly chown all cache dirs, $HOME, /opt/conda to jovyan:users - Change to Dockerfile.cache - Corrected BASE_CONTAINER ARG setup (was generating warning or error) - Fix BASE_IMAGE arg in TIKE Dockerfile (was generating warning or errors) - Switched bash.bashrc, bash.env to use env-activate instead of directly sourcing profile.sh and activating conda base env. - Dropped "Ubuntu package not found, install it?" logic in bash.env - Added yq to common.pip for slicing-and-dicing wrangler specs arbitrarily - Added additional cache cleanup code to apt-install script - Adjusted env-activate, env-clean, env-deactivate, env-conda, global_bashrc, kernel-activate.sh scripts to:     - Use mamba vs. conda according to CONDA_VER,  bug-fix really.     - Source /etc/nb-wrangler.rc to define wrangler variables in env-activate.     - Turned off -u for sourced scripts since it will kill the sourcing shell (mysteriously!) - In git-sync-v4,  overrode "rename" method of Path subclasses to use a "mv" subprocess due to platform/container failures. - Modified psh-preamble (common post-startup-hook preamble) to drop -u and env-activate base. - Added common wrangler-register-kernel script to register builtin wrangler kernel in JupyterLab - Added common wrangler-sync-notebooks script to git-sync repos found in wrangler spec - Defined wrangler config variables in common/nb-wrangler.rc - Remove cython version constraint in TIKE common-hints.conda - Added dedicated wrangler deployment for building and running environments the wragler way;  this is for auto-builds - Extra wrangler-related env vars in setup, renamed PYTHON_VERSION to BASE_PYTHON_VERSION for docker-stacks-foundation

diff --git a/setup-env.template b/setup-env.template
--- a/setup-env.template
+++ b/setup-env.template
@@ -1,19 +1,26 @@
-
+#! /bin/bash
 # Clone and customize this for your deployment
 #
 # NOTE:  must be sourced from jupyterhub-deploy root directory
 #
 
+# set -eu # DO NOT 'set -eu' since this script is sourced and will kill the sourcing terminal/shell on error.
+
 # ----------------- basic inputs,  must set for deployment --------------
 
-export DEPLOYMENT_NAME=cluster-name  # roman, jwebbinar, tike
+export DEPLOYMENT_NAME=cluster-name  # roman, jwebbinar, tike, wrangler
 export ENVIRONMENT=sandbox           # sandbox, dev, test, prod, int
 export CAL_VERSION=none              # e.g. roman or jwst x.y.z CAL release, latest, or none
 
 export USE_FROZEN=0                  # use 0 for loosely pinned package versions,
                                      # 1 for tagged/frozen production build
 
-export FREEZE=1                     # dump new frozen requirements in image to modified files in this git repo
+export FREEZE=0                     # dump new frozen requirements in image to modified files in this git repo
+
+export REPACK=0                     # repack the image to reduce size;  experimental for now, generally needed for
+                                    # wrangler scanning on github but also reduces image size permanently
+
+# https://www.perplexity.ai/search/trying-to-load-a-repacked-dock-NKu4SvlYTTq0uaram38D0w#0
 
 export PLATFORM="linux/amd64"       # os / instruction-set for built image: linux/amd64 or linux/aarch64
 
@@ -24,21 +31,32 @@ export PLATFORM="linux/amd64"       # os / instruction-set for built image: linu
 export REGISTRY=""
 # export REGISTRY="quay.io/jupyter/"
 
-
-
 # OWNER=spacetelescope will be built from docker-stacks source code
 # quay.io/jupyter has the official pre-built images,  no trailing backslash
 export OWNER="spacetelescope"
 # export OWNER="quay.io/jupyter"
 
-export BASE_IMAGE=${OWNER}/scipy-notebook   # see above
+export BASE_NOTEBOOK="scipy-notebook"  # minimal-notebook
+
+export BASE_IMAGE=${OWNER}/${BASE_NOTEBOOK}
 
 export NOTEBOOK_TAG=latest
 export NOTEBOOK_ID=notebook-${DEPLOYMENT_NAME}:${NOTEBOOK_TAG}  # abstract name of mission-specific notebook image
+# export NOTEBOOK_ID_SLIM=${NOTEBOOK_ID}-slim  # this is implied by repack,  refactor if you really need it.
+
+export DATE_TAG=$(date -u +'%Y-%m-%d-%H-%M-%S')
+export GITHUB_REG="ghcr.io"
+export GITHUB_ORG=jaytmiller
+# export GITHUB_ORG=spacetelescope
+export GITHUB_REPO=science-platform-images
+export GITHUB_TAG=notebook-${DEPLOYMENT_NAME}-${DATE_TAG}
+export GITHUB_UNTAGGED_ID=${GITHUB_REG}/${GITHUB_ORG}/${GITHUB_REPO}
+export GITHUB_IMAGE_ID=${GITHUB_REG}/${GITHUB_ORG}/${GITHUB_REPO}:${GITHUB_TAG}
+export GITHUB_IMAGE_SLIM_ID=${GITHUB_IMAGE_ID}-slim
 
 export UBUNTU_TAG="24.04"            # # Image scanning,  report Ubuntu status for this version of Ubuntu
 
-export PYTHON_VERSION="3.11"
+export BASE_PYTHON_VERSION="3.12"
 
 # ----------------- vvvv less frequently changed vvvv -------------------------------
 
