Commented out ENV in wrangler Dockerfile.custom since supplied by spec
Factored out inline setup from roman post start hook and placed it
in easy-to-read wrangler-xxx scripts in common-scripts.  These
scripts are intended to carry over to any new minimized base image
if we ever write one.

Adjusted $HOME file ownership to jovyan:users.

nb-wrangler: Automated SPI injection for spec RomanNexus-2026.2.yaml

Removed defunct "assets" folder from wranger deployment

Saved generated Dockerfile for wrangler

Added --data-clean-symlinks to wrangler-register-kernel

Removed common trailer COPY to /opt/environments since all deployments
already do it in .custom

Removed explicit wrangler install from Dockerfile in favor of
common_pip which should install it in both base and mission
environments directly from git overrides or spacetelescope main
which should be locked for production builds.

Moved implicit package installs from install-common to jupyter.pip
so they are installed as normal packages which is now possible.
Streamlined wrangler Dockerfile.custom mission environment re-install.

Added mamba-installed grype as replacement for Trivy

Pruned obsolete versions of git-sync that won't be coming back

Revised git-sync-v4 to handle tags

Corrected a number of errors and blacked git_sync_v4.py

Screened for bugs and simplifications

Made wrangler-xxx scripts executable

Added extra debug output to tests.txt

Improved log output for failed git-sync update and fallback

Fixed fallback on second sync due to blobless clone.

Added test for 2nd sync not corrupting .git

diff --git a/scripts/image-scan b/scripts/image-scan
--- a/scripts/image-scan
+++ b/scripts/image-scan
@@ -1,62 +1,27 @@
 #! /bin/bash
 
-set -e
+set -eu
 
 # If desired,  $1 can override the default image type
 export IMAGE_ID=${1:-${NOTEBOOK_ID}}
-export WHERE=${2:-""}
+export MAMBA=${2:-"micromamba"}
+export WHERE=${2:-"on-github"}
 
-
-echo "========================================================================"
-echo "WARNING:  Trivy image scanning is disabled."
-echo "========================================================================"
-exit 0
-
-# image-login
-
-export DOCKER_BUILDKIT=1
-
-TRIVY=trivy
-
-if [[ "$(which trivy)" == "" ]]; then
-    echo "The 'trivy' scanner program is not installed,  installing."
-    if [[ "$(which micromamba)" != "" ]]; then
-        MAMBA=micromamba
-    elif [[ "$(which mamba)" != "" ]]; then
-        MAMBA=mamba
-    else
-        echo "Installing micromamba first to host trivy..."
-        curl -Ls micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
-        MAMBA=bin/micromamba
-        chmod +x ${MAMBA}
-        eval "$(bin/micromamba shell hook --shell bash)"
-        ${MAMBA} config append channels conda-forge
-        ${MAMBA} config set channel_priority strict
-        ${MAMBA} self-update
-    fi
-    ${MAMBA} install --quiet -c conda-forge trivy
-    TRIVY=/home/runner/.local/share/mamba/bin/trivy
+if [[ "$(which grype)" == "" ]]; then
+    echo "The 'syft' SBOM scanner is not installed.  Installing..."
+    ${MAMBA} install --yes --quiet -c conda-forge  syft
+    echo "The 'grype' image vulnerability scanner program is not installed.  Installing..."
+    ${MAMBA} install --yes --quiet -c conda-forge  grype
 fi
 
-
-# Scanning image with trivy. https://aquasecurity.github.io/trivy/
-
-# docker run -v /var/run/docker.sock:/var/run/docker.sock \
-#       public.ecr.aws/aquasecurity/trivy:latest \
-
-function f_trivy {
-    CLI_PARAMS=$@
-    ${TRIVY}  image ${IMAGE_ID} \
-       ${CLI_PARAMS} \
-       --timeout 30m \
-       --severity HIGH,CRITICAL \
-       --scanners vuln \
-       --pkg-types os,library \
-       --parallel 1 \
-       --slow \
-       --no-progress \
-       --exit-code 1
-    return $?
+function f_grype {
+    KIND=${1:-"--only-fixed"}
+    LEVELS=${2:-"high,critical"}
+    THRESHOLD=$(echo ${LEVELS} | sed 's/,/|/g')
+    if [ ! -e /tmp/syft.sbom ]; then
+        syft --output syft-json $IMAGE_ID | cat >/tmp/syft.sbom
+    fi
+    cat /tmp/syft.sbom | grype --by-cve --output table --fail-on $THRESHOLD | grep -i -E ${LEVELS}
 }
 
 function annotated_echo {
@@ -68,27 +33,25 @@ function annotated_echo {
     fi
 }
 
-echo "scanfailed" >/tmp/trivy-tag   # this may be impossible but just in case
+echo "scanfailed" >/tmp/grype-tag   # this may be impossible but just in case
 
-set -o pipefail         # do not stop if f_trivy fails in a pipe
+set -o pipefail         # do not stop if f_grype fails in a pipe
 set +e                  # do not stop on error
 
-# Run Trivy and suppress initial output until Legend: is seen
-f_trivy | awk '/^Legend:/ {found=1} found {print}'
-
+f_grype --only-fixed high,critical
 if [ $? -ne 0 ]; then
-    annotated_echo "===> Trivy scan FAILED w/o --ignore-unfixed."
-    OUTPUT=$(f_trivy --ignore-unfixed)
+    annotated_echo "===> Grype scan FAILED w/o --only-fixed."
+    f_grype --only-unfixed high,critical
     if [ $? -ne 0 ]; then
-        annotated_echo "===> Trivy scan FAILED with --ignore-unfixed."
-        echo "hasfixed" >/tmp/trivy-tag
+        annotated_echo "===> Grype scan FAILED with --only-fixed."
+        echo "hasfixed" >/tmp/grype-tag
     else
-        annotated_echo "===> Trivy scan PASSED with --ignore-unfixed."
-        echo "hasunfixed" >/tmp/trivy-tag
+        annotated_echo "===> Grype scan PASSED with --only-unfixed."
+        echo "hasunfixed" >/tmp/grype-tag
     fi
-    # exit 1
+    exit 1
 else
-    echo "===> Trivy scan PASSED even w/o --ignore-unfixed."
-    echo "scanok" >/tmp/trivy-tag
+    echo "===> Grype scan PASSED even w/o --only-fixed."
+    echo "scanok" >/tmp/grype-tag
 fi
 exit 0
