Additional changes related to porting from AWS, whether past or present. Migrated SW_INSTALLS.md about user persistent kernel creation scripts    which are built into the image but really only apply to the hub. Removed instance of CLEAR_PKG_CACHES from infrequent-env. Dropped git-remote-codecommit unneeded for GitHub from requirements.txt Ported new ruff source code scanning. Added ruff, checkov to requirements.txt. Added ruff scanning to code quality workflow Added branch-changes-obj script for conditional builds Adjusted build-test workflow for single mission conditional builds Updated image-chill script to handle common-hints.pip files. Added common-hints.pip to chilled requirements.

diff --git a/scripts/sscan b/scripts/sscan
--- a/scripts/sscan
+++ b/scripts/sscan
@@ -23,6 +23,12 @@ sscan-flake8
 flake8_status=$?
 
 echo "====================================================="
+echo "Scanning source code for quality with ruff           "
+echo "====================================================="
+sscan-ruff
+ruff_status=$?
+
+echo "====================================================="
 echo "Scanning source code for vulnerabilities using bandit"
 echo "====================================================="
 sscan-bandit
@@ -43,11 +49,17 @@ else
     echo "OK - Flake8 Python code quality checks."
 fi
 
+if [[ "$ruff_status" == "1" ]]; then
+    echo "ERROR - Ruff Python code quality checks failed."
+else
+    echo "OK - Ruff Python code quality checks."
+fi
+
 if [[ "$bandit_status" == "1" ]]; then
     echo "ERROR - Bandit source code security scanning found vulnerabilities."
 else
     echo "OK - Bandit source code security scanning."
 fi
 
-fail=`expr $yaml_status + $flake8_status + $bandit_status `
+fail=`expr $yaml_status + $flake8_status + $ruff_status + $bandit_status`
 exit $fail
